BREADBOARD_WIDTH = 1720
BREADBOARD_HEIGHT = 534

MENU_HEIGHT = 70

DISPLAY_WIDTH = BREADBOARD_WIDTH
DISPLAY_HEIGHT = MENU_HEIGHT + BREADBOARD_HEIGHT

WIRE_X_OFFSET = 6
WIRE_Y_OFFSET = 6
DIODE_X_OFFSET = 2
